using System.Collections.Generic;

namespace SkanderNET
{
    public class HatIndex
    {
        public static readonly Dictionary<int, string> Hats = new Dictionary<int, string>()
        {
            {0, "No Hat"},
            {1, "Combat Hat"},
            {2, "Napoleon Hat"},
            {3, "Spy Gear"},
            {4, "Miner Hat"},
            {5, "General's Hat"},
            {6, "Pirate Hat"},
            {7, "Propeller Cap"},
            {8, "Coonskin Cap"},
            {9, "Straw Hat"},
            {10, "Fancy Hat"},
            {11, "Top Hat"},
            {12, "Viking Helmet"},
            {13, "Spiked Hat"},
            {14, "Anvil Hat"},
            {15, "Beret"},
            {16, "Birthday Hat"},
            {17, "Bone Head"},
            {18, "Bowler Hat"},
            {19, "Wabbit Ears"},
            {20, "Tropical Turban"},
            {21, "Chef Hat"},
            {22, "Cowboy Hat"},
            {23, "Rocker Hair"},
            {24, "Royal Crown"},
            {25, "Lil Devil"},
            {26, "Eye Hat"},
            {27, "Fez"},
            {28, "Crown of Light"},
            {29, "Jester Hat"},
            {30, "Winged Hat"},
            {31, "Moose Hat"},
            {32, "Plunger Head"},
            {33, "Pan Hat"},
            {34, "Rocket Hat"},
            {35, "Santa Hat"},
            {36, "Tiki Hat"},
            {37, "Trojan Helmet"},
            {38, "Unicorn Hat"},
            {39, "Wizard Hat"},
            {40, "Pumpkin Hat"},
            {41, "Pirate Doo Rag"},
            {42, "Cossack Hat"},
            {43, "Flower Hat"},
            {44, "Balloon Hat"},
            {45, "Happy Birthday!"},
            {46, "Vintage Baseball Cap"},
            {47, "Bowling Pin Hat"},
            {48, "Officer Cap"},
            {49, "Firefighter Helmet"},
            {50, "Graduation Hat"},
            {51, "Lampshade Hat"},
            {52, "Mariachi Hat"},
            {53, "Paper Fast Food Hat"},
            {54, "Pilgrim Hat"},
            {55, "Police Siren Hat"},
            {56, "Purple Fedora"},
            {57, "Archer Hat"},
            {58, "Safari Hat"},
            {59, "Sailor Hat"},
            {60, "Dancer Hat"},
            {61, "Traffic Cone Hat"},
            {62, "Turban"},
            {63, "Battle Helmet"},
            {64, "Bottle Cap Hat"},
            {65, "Carrot Hat"},
            {66, "Elf Hat"},
            {67, "Fishing Hat"},
            {68, "Future Hat"},
            {69, "Nefertiti Hat"},
            {70, "Pants Hat"},
            {71, "Princess Hat"},
            {72, "Toy Solider Hat"},
            {73, "Trucker Hat"},
            {74, "Umbrella Hat"},
            {75, "Showtime Hat"},
            {76, "Caesar Hat"},
            {77, "Flower Fairy Hat"},
            {78, "Funnel Hat"},
            {79, "Scrumshanks Hat"},
            {80, "Biter Hat"},
            {81, "Atom Hat"},
            {82, "Sombrero"},
            {83, "Rasta Hat"},
            {84, "Kufi Hat"},
            {85, "Knight Helm"},
            {86, "Dangling Carrot Hat"},
            {87, "Bronze Top Hat"},
            {88, "Silver Top Hat"},
            {89, "Gold Top Hat"},
        };

    }
}