using System.Collections.Generic;

namespace SkanderNET
{
    public enum SkylanderElement
    {
        None,
        Air,
        Earth,
        Fire,
        Water,
        Magic,
        Tech,
        Life,
        Undead,
        Light,
        Dark,
        Kaos
    }

    public enum SkylanderType
    {
        Skylander,
        MagicItem,
        AdventurePack,
        Trap,
        Vehicle,
        Crystal,
    }
    
    public class SkylanderGenericData
    {
        public readonly ushort Id;
        public readonly ushort Variant;
        public readonly string Name;
        public readonly SkylanderElement Element;
        public readonly SkylanderType Type;

        public SkylanderGenericData(ushort id, ushort variant, string name, SkylanderElement element = SkylanderElement.None, SkylanderType type =  SkylanderType.Skylander)
        {
            Id = id;
            Variant = variant;
            Name = name;
            Element = element;
            Type = type;
        }
    }

    public abstract class SkylanderIndex
    {
        public static readonly List<SkylanderGenericData> Skylanders = new List<SkylanderGenericData>
        {
            new SkylanderGenericData(0x0, 0x0000, "Whirlwind", SkylanderElement.Air),
            new SkylanderGenericData(0x0, 0x1801, "Whirlwind (Series 2)", SkylanderElement.Air),
            new SkylanderGenericData(0x0, 0x1C02, "Polar Whirlwind", SkylanderElement.Air),
            new SkylanderGenericData(0x0, 0x2805, "Horn Blast Whirlwind", SkylanderElement.Air),
            new SkylanderGenericData(0x0, 0x3810, "Whirlwind (Eon's Elite)", SkylanderElement.Air),
            new SkylanderGenericData(0x1, 0x0000, "Sonic Boom", SkylanderElement.Air),
            new SkylanderGenericData(0x1, 0x1801, "Sonic Boom (Series 2)", SkylanderElement.Air),
            new SkylanderGenericData(0x1, 0x1811, "Sonic Boom (Glow in the Dark)", SkylanderElement.Air),
            new SkylanderGenericData(0x1, 0x1813, "Sonic Boom (Glitter)", SkylanderElement.Air),
            new SkylanderGenericData(0x2, 0x0000, "Warnado", SkylanderElement.Air),
            new SkylanderGenericData(0x2, 0x2206, "Warnado (LightCore)", SkylanderElement.Air),
            new SkylanderGenericData(0x3, 0x0000, "Lightning Rod", SkylanderElement.Air),
            new SkylanderGenericData(0x3, 0x1801, "Lightning Rod (Series 2)", SkylanderElement.Air),
            new SkylanderGenericData(0x3, 0x1814, "Lightning Rod (Iridescent)", SkylanderElement.Air),
            new SkylanderGenericData(0x4, 0x0000, "Bash", SkylanderElement.Earth),
            new SkylanderGenericData(0x4, 0x1801, "Bash (Series 2)", SkylanderElement.Earth),
            new SkylanderGenericData(0x5, 0x0000, "Terrafin", SkylanderElement.Earth),
            new SkylanderGenericData(0x5, 0x1801, "Terrafin (Series 2)", SkylanderElement.Earth),
            new SkylanderGenericData(0x5, 0x2805, "Knockout Terrafin", SkylanderElement.Earth),
            new SkylanderGenericData(0x5, 0x3810, "Terrafin (Eon's Elite)", SkylanderElement.Earth),
            new SkylanderGenericData(0x6, 0x0000, "Dino Rang", SkylanderElement.Earth),
            new SkylanderGenericData(0x6, 0x4810, "Dino Rang (Eon's Elite)", SkylanderElement.Earth),
            new SkylanderGenericData(0x7, 0x0000, "Prism Break", SkylanderElement.Earth),
            new SkylanderGenericData(0x7, 0x1801, "Prism Break (Series 2)", SkylanderElement.Earth),
            new SkylanderGenericData(0x7, 0x2805, "Hyper Beam Prism Break", SkylanderElement.Earth),
            new SkylanderGenericData(0x7, 0x1206, "Prism Break (LightCore)", SkylanderElement.Earth),
            new SkylanderGenericData(0x7, 0x1214, "Prism Break (LightCore Rare)", SkylanderElement.Earth),
            new SkylanderGenericData(0x8, 0x0000, "Sunburn", SkylanderElement.Fire),
            new SkylanderGenericData(0x9, 0x0000, "Eruptor", SkylanderElement.Fire),
            new SkylanderGenericData(0x9, 0x1801, "Eruptor (Series 2)", SkylanderElement.Fire),
            new SkylanderGenericData(0x9, 0x1814, "Eruptor (White Flocked)", SkylanderElement.Fire),
            new SkylanderGenericData(0x9, 0x2C02, "Volcanic Eruptor", SkylanderElement.Fire),
            new SkylanderGenericData(0x9, 0x2805, "Lava Barf Eruptor", SkylanderElement.Fire),
            new SkylanderGenericData(0x9, 0x1206, "Eruptor (LightCore)", SkylanderElement.Fire),
            new SkylanderGenericData(0x9, 0x3810, "Eruptor (Eon's Elite)", SkylanderElement.Fire),
            new SkylanderGenericData(0xa, 0x0000, "Ignitor", SkylanderElement.Fire),
            new SkylanderGenericData(0xa, 0x1801, "Ignitor (Series 2)", SkylanderElement.Fire),
            new SkylanderGenericData(0xa, 0x1C03, "Legendary Ignitor", SkylanderElement.Fire),
            new SkylanderGenericData(0xb, 0x0000, "Flameslinger", SkylanderElement.Fire),
            new SkylanderGenericData(0xb, 0x1801, "Flameslinger (Series 2)", SkylanderElement.Fire),
            new SkylanderGenericData(0xc, 0x0000, "Zap", SkylanderElement.Water),
            new SkylanderGenericData(0xc, 0x1801, "Zap (Series 2)", SkylanderElement.Water),
            new SkylanderGenericData(0xd, 0x0000, "Wham Shell", SkylanderElement.Water),
            new SkylanderGenericData(0xd, 0x2206, "Wham Shell (LightCore)", SkylanderElement.Water),
            new SkylanderGenericData(0xe, 0x0000, "Gill Grunt", SkylanderElement.Water),
            new SkylanderGenericData(0xe, 0x1801, "Gill Grunt (Series 2)", SkylanderElement.Water),
            new SkylanderGenericData(0xe, 0x1817, "Gill Grunt (Metallic)", SkylanderElement.Water),
            new SkylanderGenericData(0xe, 0x2805, "Anchors Away Gill Grunt", SkylanderElement.Water),
            new SkylanderGenericData(0xe, 0x3805, "Tidal Wave Gill Grunt", SkylanderElement.Water),
            new SkylanderGenericData(0xe, 0x3810, "Gill Grunt (Eon's Elite)", SkylanderElement.Water),
            new SkylanderGenericData(0xf, 0x0000, "Slam Bam", SkylanderElement.Water),
            new SkylanderGenericData(0xf, 0x1801, "Slam Bam (Series 2)", SkylanderElement.Water),
            new SkylanderGenericData(0xf, 0x1C03, "Legendary Slam Bam", SkylanderElement.Water),
            new SkylanderGenericData(0xf, 0x4810, "Slam Bam (Eon's Elite)", SkylanderElement.Water),
            new SkylanderGenericData(0x10, 0x0000, "Spyro", SkylanderElement.Magic),
            new SkylanderGenericData(0x10, 0x1801, "Spyro (Series 2)", SkylanderElement.Magic),
            new SkylanderGenericData(0x10, 0x2C02, "Dark Mega Ram Spyro", SkylanderElement.Magic),
            new SkylanderGenericData(0x10, 0x2805, "Mega Ram Spyro", SkylanderElement.Magic),
            new SkylanderGenericData(0x10, 0x3810, "Spyro (Eon's Elite)", SkylanderElement.Magic),
            new SkylanderGenericData(0x11, 0x0000, "Voodood", SkylanderElement.Magic),
            new SkylanderGenericData(0x11, 0x4810, "Voodood (Eon's Elite)", SkylanderElement.Magic),
            new SkylanderGenericData(0x12, 0x0000, "Double Trouble", SkylanderElement.Magic),
            new SkylanderGenericData(0x12, 0x1801, "Double Trouble (Series 2)", SkylanderElement.Magic),
            new SkylanderGenericData(0x12, 0x1C02, "Royal Double Trouble", SkylanderElement.Magic),
            new SkylanderGenericData(0x13, 0x0000, "Trigger Happy", SkylanderElement.Tech),
            new SkylanderGenericData(0x13, 0x1801, "Trigger Happy (Series 2)", SkylanderElement.Tech),
            new SkylanderGenericData(0x13, 0x2C02, "Springtime Trigger Happy", SkylanderElement.Tech),
            new SkylanderGenericData(0x13, 0x2805, "Big Bang Trigger Happy", SkylanderElement.Tech),
            new SkylanderGenericData(0x13, 0x3810, "Trigger Happy (Eon's Elite)", SkylanderElement.Tech),
            new SkylanderGenericData(0x14, 0x0000, "Drobot", SkylanderElement.Tech),
            new SkylanderGenericData(0x14, 0x1801, "Drobot (Series 2)", SkylanderElement.Tech),
            new SkylanderGenericData(0x14, 0x1206, "Drobot (LightCore)", SkylanderElement.Tech),
            new SkylanderGenericData(0x15, 0x0000, "Drill Sergeant", SkylanderElement.Tech),
            new SkylanderGenericData(0x15, 0x1801, "Drill Sergeant (Series 2)", SkylanderElement.Tech),
            new SkylanderGenericData(0x16, 0x0000, "Boomer", SkylanderElement.Tech),
            new SkylanderGenericData(0x16, 0x4810, "Boomer (Eon's Elite)", SkylanderElement.Tech),
            new SkylanderGenericData(0x17, 0x0000, "Wrecking Ball", SkylanderElement.Magic),
            new SkylanderGenericData(0x17, 0x1801, "Wrecking Ball (Series 2)", SkylanderElement.Magic),
            new SkylanderGenericData(0x17, 0x1814, "Wrecking Ball (Iridescent)", SkylanderElement.Magic),
            new SkylanderGenericData(0x18, 0x0000, "Camo", SkylanderElement.Life),
            new SkylanderGenericData(0x18, 0x2805, "Thorn Horn Camo", SkylanderElement.Life),
            new SkylanderGenericData(0x19, 0x0000, "Zook", SkylanderElement.Life),
            new SkylanderGenericData(0x19, 0x1801, "Zook (Series 2)", SkylanderElement.Life),
            new SkylanderGenericData(0x19, 0x1812, "Zook (Stone)", SkylanderElement.Life),
            new SkylanderGenericData(0x19, 0x4810, "Zook (Eon's Elite)", SkylanderElement.Life),
            new SkylanderGenericData(0x1a, 0x0000, "Stealth Elf", SkylanderElement.Life),
            new SkylanderGenericData(0x1a, 0x1801, "Stealth Elf (Series 2)", SkylanderElement.Life),
            new SkylanderGenericData(0x1a, 0x2C02, "Dark Stealth Elf", SkylanderElement.Life),
            new SkylanderGenericData(0x1a, 0x1C03, "Legendary Stealth Elf", SkylanderElement.Life),
            new SkylanderGenericData(0x1a, 0x2805, "Ninja Stealth Elf", SkylanderElement.Life),
            new SkylanderGenericData(0x1a, 0x3810, "Stealth Elf (Eon's Elite)", SkylanderElement.Life),
            new SkylanderGenericData(0x1b, 0x0000, "Stump Smash", SkylanderElement.Life),
            new SkylanderGenericData(0x1b, 0x1801, "Stump Smash (Series 2)", SkylanderElement.Life),
            new SkylanderGenericData(0x1b, 0x1814, "Stump Smash (White Flocked)", SkylanderElement.Life),
            new SkylanderGenericData(0x1c, 0x0000, "Dark Spyro", SkylanderElement.Magic),
            new SkylanderGenericData(0x1d, 0x0000, "Hex", SkylanderElement.Undead),
            new SkylanderGenericData(0x1d, 0x1801, "Hex (Series 2)", SkylanderElement.Undead),
            new SkylanderGenericData(0x1d, 0x1206, "Hex (LightCore)", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e, 0x0000, "Chop Chop", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e, 0x1801, "Chop Chop (Series 2)", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e, 0x1804, "Chop Chop (Metallic)", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e, 0x2816, "Chop Chop (Green)", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e, 0x2805, "Twin Blade Chop Chop", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e, 0x3810, "Chop Chop (Eon's Elite)", SkylanderElement.Undead),
            new SkylanderGenericData(0x1f, 0x0000, "Ghost Roaster", SkylanderElement.Undead),
            new SkylanderGenericData(0x1f, 0x4810, "Ghost Roaster (Eon's Elite)", SkylanderElement.Undead),
            new SkylanderGenericData(0x20, 0x0000, "Cynder", SkylanderElement.Undead),
            new SkylanderGenericData(0x20, 0x1801, "Cynder (Series 2)", SkylanderElement.Undead),
            new SkylanderGenericData(0x20, 0x1811, "Cynder (Glow in the Dark)", SkylanderElement.Undead),
            new SkylanderGenericData(0x20, 0x2805, "Phantom Cynder", SkylanderElement.Undead),
            new SkylanderGenericData(0x64, 0x1000, "Jet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0x64, 0x1403, "Legendary Jet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0x64, 0x2805, "Turbo Jet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0x64, 0x3805, "Full Blast Jet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0x64, 0x1206, "Jet Vac (LightCore)", SkylanderElement.Air),
            new SkylanderGenericData(0x65, 0x1206, "Swarm", SkylanderElement.Air),
            new SkylanderGenericData(0x66, 0x1206, "Crusher", SkylanderElement.Earth),
            new SkylanderGenericData(0x66, 0x1602, "Granite Crusher", SkylanderElement.Earth),
            new SkylanderGenericData(0x67, 0x1000, "Flashwing", SkylanderElement.Earth),
            new SkylanderGenericData(0x67, 0x1402, "Jade Flash Wing", SkylanderElement.Earth),
            new SkylanderGenericData(0x67, 0x2206, "Flashwing (LightCore)", SkylanderElement.Earth),
            new SkylanderGenericData(0x68, 0x1206, "Hot Head", SkylanderElement.Fire),
            new SkylanderGenericData(0x68, 0x1213, "Hot Head (Glitter)", SkylanderElement.Fire),
            new SkylanderGenericData(0x69, 0x1000, "Hot Dog", SkylanderElement.Fire),
            new SkylanderGenericData(0x69, 0x281A, "Hot Dog (Red Frito-Lay)", SkylanderElement.Fire),
            new SkylanderGenericData(0x69, 0x281B, "Hot Dog (Green Frito-Lay)", SkylanderElement.Fire),
            new SkylanderGenericData(0x69, 0x281C, "Hot Dog (Purple Frito-Lay)", SkylanderElement.Fire),
            new SkylanderGenericData(0x69, 0x1402, "Molten Hot Dog", SkylanderElement.Fire),
            new SkylanderGenericData(0x69, 0x2805, "Fire Bone Hot Dog", SkylanderElement.Fire),
            new SkylanderGenericData(0x6a, 0x1000, "Chill", SkylanderElement.Water),
            new SkylanderGenericData(0x6a, 0x1603, "Legendary Chill", SkylanderElement.Water),
            new SkylanderGenericData(0x6a, 0x2805, "Blizzard Chill", SkylanderElement.Water),
            new SkylanderGenericData(0x6a, 0x1206, "Chill (LightCore)", SkylanderElement.Water),
            new SkylanderGenericData(0x6b, 0x1206, "Thumpback", SkylanderElement.Water),
            new SkylanderGenericData(0x6c, 0x1000, "Pop Fizz", SkylanderElement.Magic),
            new SkylanderGenericData(0x6c, 0x1402, "Punch Pop Fizz", SkylanderElement.Magic),
            new SkylanderGenericData(0x6c, 0x3C02, "Love Potion Pop Fizz", SkylanderElement.Magic),
            new SkylanderGenericData(0x6c, 0x2805, "Super Gulp Pop Fizz", SkylanderElement.Magic),
            new SkylanderGenericData(0x6c, 0x3805, "Fizzy Frenzy Pop Fizz", SkylanderElement.Magic),
            new SkylanderGenericData(0x6c, 0x1206, "Pop Fizz (LightCore)", SkylanderElement.Magic),
            new SkylanderGenericData(0x6d, 0x1206, "Ninjini", SkylanderElement.Magic),
            new SkylanderGenericData(0x6d, 0x1602, "Scarlet Ninjini", SkylanderElement.Magic),
            new SkylanderGenericData(0x6e, 0x1206, "Bouncer", SkylanderElement.Tech),
            new SkylanderGenericData(0x6e, 0x1603, "Legendary Bouncer", SkylanderElement.Tech),
            new SkylanderGenericData(0x6f, 0x1000, "Sprocket", SkylanderElement.Tech),
            new SkylanderGenericData(0x6f, 0x2805, "Heavy Duty Sprocket", SkylanderElement.Tech),
            new SkylanderGenericData(0x70, 0x1206, "Tree Rex", SkylanderElement.Life),
            new SkylanderGenericData(0x70, 0x1602, "Gnarly Tree Rex", SkylanderElement.Life),
            new SkylanderGenericData(0x71, 0x1000, "Shroomboom", SkylanderElement.Life),
            new SkylanderGenericData(0x71, 0x3805, "Sure Shot Shroomboom", SkylanderElement.Life),
            new SkylanderGenericData(0x71, 0x1206, "Shroomboom (LightCore)", SkylanderElement.Life),
            new SkylanderGenericData(0x71, 0x1017, "Shroomboom (Metalic)", SkylanderElement.Life),
            new SkylanderGenericData(0x72, 0x1206, "Eye Brawl", SkylanderElement.Undead),
            new SkylanderGenericData(0x72, 0x1214, "Eye Brawl (Iridescent)", SkylanderElement.Undead),
            new SkylanderGenericData(0x72, 0x1215, "Eye Brawl (Pumpkin)", SkylanderElement.Undead),
            new SkylanderGenericData(0x73, 0x1000, "Fright Rider", SkylanderElement.Undead),
            new SkylanderGenericData(0xc8, 0x0000, "Anvil Rain", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xc9, 0x0000, "Hidden Treasure", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xc9, 0x1000, "Platinum Hidden Treasure", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xca, 0x0000, "Healing Elixir", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xcb, 0x0000, "Ghost Pirate Swords", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xcc, 0x0000, "Time Twist Hourglass", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xcd, 0x0000, "Sky Iron Shield", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xce, 0x0000, "Winged Boots", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xcf, 0x0000, "Sparx the Dragonfly", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xd0, 0x1206, "Dragonfire Cannon", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xd0, 0x1602, "Golden Dragonfire Cannon", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xd1, 0x1206, "Scorpion Striker", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xd2, 0x3002, "Biter's Bane", SkylanderElement.Magic, SkylanderType.Trap),
            new SkylanderGenericData(0xd2, 0x3008, "Sorcerous Skull", SkylanderElement.Magic, SkylanderType.Trap),
            new SkylanderGenericData(0xd2, 0x300B, "Axe of Illusion", SkylanderElement.Magic, SkylanderType.Trap),
            new SkylanderGenericData(0xd2, 0x300E, "Arcane Hourglass", SkylanderElement.Magic, SkylanderType.Trap),
            new SkylanderGenericData(0xd2, 0x3012, "Spell Slapper", SkylanderElement.Magic, SkylanderType.Trap),
            new SkylanderGenericData(0xd2, 0x3014, "Rune Rocket", SkylanderElement.Magic, SkylanderType.Trap),
            new SkylanderGenericData(0xd3, 0x3001, "Tidal Tiki", SkylanderElement.Water, SkylanderType.Trap),
            new SkylanderGenericData(0xd3, 0x3002, "Wet Walter", SkylanderElement.Water, SkylanderType.Trap),
            new SkylanderGenericData(0xd3, 0x3006, "Flood Flask", SkylanderElement.Water, SkylanderType.Trap),
            new SkylanderGenericData(0xd3, 0x3406, "Legendary Flood Flask", SkylanderElement.Water, SkylanderType.Trap),
            new SkylanderGenericData(0xd3, 0x3007, "Soaking Staff", SkylanderElement.Water, SkylanderType.Trap),
            new SkylanderGenericData(0xd3, 0x300B, "Aqua Axe", SkylanderElement.Water, SkylanderType.Trap),
            new SkylanderGenericData(0xd3, 0x3016, "Frost Helm", SkylanderElement.Water, SkylanderType.Trap),
            new SkylanderGenericData(0xd4, 0x3003, "Breezy Bird", SkylanderElement.Air, SkylanderType.Trap),
            new SkylanderGenericData(0xd4, 0x3006, "Drafty Decanter", SkylanderElement.Air, SkylanderType.Trap),
            new SkylanderGenericData(0xd4, 0x300D, "Tempest Timer", SkylanderElement.Air, SkylanderType.Trap),
            new SkylanderGenericData(0xd4, 0x3010, "Cloudy Cobra", SkylanderElement.Air, SkylanderType.Trap),
            new SkylanderGenericData(0xd4, 0x3011, "Storm Warning", SkylanderElement.Air, SkylanderType.Trap),
            new SkylanderGenericData(0xd4, 0x3018, "Cyclone Saber", SkylanderElement.Air, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x3004, "Spirit Sphere", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x3404, "Legendary Spirit Sphere", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x3008, "Spectral Skull", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x3408, "Legendary Spectral Skull", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x300B, "Haunted Hatchet", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x300C, "Grim Gripper", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x3010, "Spooky Snake", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd5, 0x3017, "Dream Piercer", SkylanderElement.Undead, SkylanderType.Trap),
            new SkylanderGenericData(0xd6, 0x3000, "Tech Totem", SkylanderElement.Tech, SkylanderType.Trap),
            new SkylanderGenericData(0xd6, 0x3007, "Automatic Angel", SkylanderElement.Tech, SkylanderType.Trap),
            new SkylanderGenericData(0xd6, 0x3009, "Factory Flower", SkylanderElement.Tech, SkylanderType.Trap),
            new SkylanderGenericData(0xd6, 0x300C, "Grabbing Gadget", SkylanderElement.Tech, SkylanderType.Trap),
            new SkylanderGenericData(0xd6, 0x3016, "Makers Mana", SkylanderElement.Tech, SkylanderType.Trap),
            new SkylanderGenericData(0xd6, 0x301A, "Topsy Techy", SkylanderElement.Tech, SkylanderType.Trap),
            new SkylanderGenericData(0xd7, 0x3005, "Eternal Flame", SkylanderElement.Fire, SkylanderType.Trap),
            new SkylanderGenericData(0xd7, 0x3009, "Fire Flower", SkylanderElement.Fire, SkylanderType.Trap),
            new SkylanderGenericData(0xd7, 0x3011, "Scorching Stopper", SkylanderElement.Fire, SkylanderType.Trap),
            new SkylanderGenericData(0xd7, 0x3012, "Searing Spinner", SkylanderElement.Fire, SkylanderType.Trap),
            new SkylanderGenericData(0xd7, 0x3017, "Spark Spear", SkylanderElement.Fire, SkylanderType.Trap),
            new SkylanderGenericData(0xd7, 0x301B, "Blazing Belch", SkylanderElement.Fire, SkylanderType.Trap),
            new SkylanderGenericData(0xd8, 0x3000, "Banded Boulder", SkylanderElement.Earth, SkylanderType.Trap),
            new SkylanderGenericData(0xd8, 0x3003, "Rock Hawk", SkylanderElement.Earth, SkylanderType.Trap),
            new SkylanderGenericData(0xd8, 0x300A, "Slag Hammer", SkylanderElement.Earth, SkylanderType.Trap),
            new SkylanderGenericData(0xd8, 0x300E, "Dust Of Time", SkylanderElement.Earth, SkylanderType.Trap),
            new SkylanderGenericData(0xd8, 0x3013, "Spinning Sandstorm", SkylanderElement.Earth, SkylanderType.Trap),
            new SkylanderGenericData(0xd8, 0x301A, "Rubble Trouble", SkylanderElement.Earth, SkylanderType.Trap),
            new SkylanderGenericData(0xd9, 0x3003, "Oak Eagle", SkylanderElement.Life, SkylanderType.Trap),
            new SkylanderGenericData(0xd9, 0x3005, "Emerald Energy", SkylanderElement.Life, SkylanderType.Trap),
            new SkylanderGenericData(0xd9, 0x300A, "Weed Whacker", SkylanderElement.Life, SkylanderType.Trap),
            new SkylanderGenericData(0xd9, 0x3010, "Seed Serpent", SkylanderElement.Life, SkylanderType.Trap),
            new SkylanderGenericData(0xd9, 0x3018, "Jade Blade", SkylanderElement.Life, SkylanderType.Trap),
            new SkylanderGenericData(0xd9, 0x301B, "Shrub Shrieker", SkylanderElement.Life, SkylanderType.Trap),
            new SkylanderGenericData(0xda, 0x3000, "Dark Dagger", SkylanderElement.Dark, SkylanderType.Trap),
            new SkylanderGenericData(0xda, 0x3014, "Shadow Spider", SkylanderElement.Dark, SkylanderType.Trap),
            new SkylanderGenericData(0xda, 0x301A, "Ghastly Grimace", SkylanderElement.Dark, SkylanderType.Trap),
            new SkylanderGenericData(0xdb, 0x3000, "Shining Ship", SkylanderElement.Light, SkylanderType.Trap),
            new SkylanderGenericData(0xdb, 0x300F, "Heavenly Hawk", SkylanderElement.Light, SkylanderType.Trap),
            new SkylanderGenericData(0xdb, 0x301B, "Beam Scream", SkylanderElement.Light, SkylanderType.Trap),
            new SkylanderGenericData(0xdc, 0x301E, "Kaos Trap", SkylanderElement.Kaos, SkylanderType.Trap),
            new SkylanderGenericData(0xdc, 0x351F, "Ultimate Kaos Trap", SkylanderElement.Kaos, SkylanderType.Trap),
            new SkylanderGenericData(0xe6, 0x0000, "Hand of Fate", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xe6, 0x3403, "Legendary Hand of Fate", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xe7, 0x3000, "Piggy Bank", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xe8, 0x3000, "Rocket Ram", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xeb, 0x3000, "Tiki Speaky", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xeb, 0x5001, "Mystery Chest (Bronze)", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xeb, 0x5002, "Mystery Chest (Silver)", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xeb, 0x5003, "Mystery Chest (Gold)", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xeb, 0x5017, "Mystery Chest (Cursed Tiki Temple)", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xeb, 0x5019, "Mystery Chest (Lost Imaginite Mines)", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0x12c, 0x0000, "Dragon’s Peak", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x12d, 0x0000, "Empire of Ice", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x12e, 0x0000, "Pirate Seas", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x12f, 0x0000, "Darklight Crypt", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x130, 0x0000, "Volcanic Vault", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x131, 0x3000, "Mirror of Mystery", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x132, 0x3000, "Nightmare Express", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x133, 0x3206, "Sunscraper Spire", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x134, 0x3000, "Midnight Museum", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x134, 0x3206, "Midnight Museum (LightCore)", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x136, 0x5000, "Gryphon Park Observatory", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x137, 0x5000, "Enchanted Elven Forest", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0x194, 0x0000, "Legendary Bash", SkylanderElement.Earth),
            new SkylanderGenericData(0x1a0, 0x0000, "Legendary Spyro", SkylanderElement.Magic),
            new SkylanderGenericData(0x1a3, 0x0000, "Legendary Trigger Happy", SkylanderElement.Tech),
            new SkylanderGenericData(0x1ae, 0x0000, "Legendary Chop Chop", SkylanderElement.Undead),
            new SkylanderGenericData(0x1c2, 0x3000, "Gusto", SkylanderElement.Air),
            new SkylanderGenericData(0x1c3, 0x3000, "Thunderbolt", SkylanderElement.Air),
            new SkylanderGenericData(0x1c3, 0x301D, "Thunderbolt (Clear)", SkylanderElement.Air),
            new SkylanderGenericData(0x1c4, 0x3000, "Fling Kong", SkylanderElement.Air),
            new SkylanderGenericData(0x1c5, 0x3000, "Blades", SkylanderElement.Air),
            new SkylanderGenericData(0x1c5, 0x3403, "Legendary Blades", SkylanderElement.Air),
            new SkylanderGenericData(0x1c6, 0x3000, "Wallop", SkylanderElement.Earth),
            new SkylanderGenericData(0x1c7, 0x3000, "Head Rush", SkylanderElement.Earth),
            new SkylanderGenericData(0x1c7, 0x3402, "Nitro Head Rush", SkylanderElement.Earth),
            new SkylanderGenericData(0x1c8, 0x3000, "Fist Bump", SkylanderElement.Earth),
            new SkylanderGenericData(0x1c9, 0x3000, "Rocky Roll", SkylanderElement.Earth),
            new SkylanderGenericData(0x1ca, 0x3000, "Wildfire", SkylanderElement.Fire),
            new SkylanderGenericData(0x1ca, 0x3402, "Dark Wildfire", SkylanderElement.Fire),
            new SkylanderGenericData(0x1cb, 0x3000, "Ka Boom", SkylanderElement.Fire),
            new SkylanderGenericData(0x1cc, 0x3000, "Trail Blazer", SkylanderElement.Fire),
            new SkylanderGenericData(0x1cd, 0x3000, "Torch", SkylanderElement.Fire),
            new SkylanderGenericData(0x1ce, 0x3000, "Snap Shot", SkylanderElement.Water),
            new SkylanderGenericData(0x1ce, 0x3402, "Dark Snap Shot", SkylanderElement.Water),
            new SkylanderGenericData(0x1cf, 0x3000, "Lob Star", SkylanderElement.Water),
            new SkylanderGenericData(0x1cf, 0x3402, "Winterfest Lob-Star", SkylanderElement.Water),
            new SkylanderGenericData(0x1d0, 0x3000, "Flip Wreck", SkylanderElement.Water),
            new SkylanderGenericData(0x1d1, 0x3000, "Echo", SkylanderElement.Water),
            new SkylanderGenericData(0x1d2, 0x3000, "Blastermind", SkylanderElement.Magic),
            new SkylanderGenericData(0x1d3, 0x3000, "Enigma", SkylanderElement.Magic),
            new SkylanderGenericData(0x1d4, 0x3000, "Deja Vu", SkylanderElement.Magic),
            new SkylanderGenericData(0x1d4, 0x3403, "Legendary Deja Vu", SkylanderElement.Magic),
            new SkylanderGenericData(0x1d5, 0x3000, "Cobra Candabra", SkylanderElement.Magic),
            new SkylanderGenericData(0x1d5, 0x3402, "King Cobra Cadabra", SkylanderElement.Magic),
            new SkylanderGenericData(0x1d6, 0x3000, "Jawbreaker", SkylanderElement.Tech),
            new SkylanderGenericData(0x1d6, 0x3403, "Legendary Jawbreaker", SkylanderElement.Tech),
            new SkylanderGenericData(0x1d7, 0x3000, "Gearshift", SkylanderElement.Tech),
            new SkylanderGenericData(0x1d8, 0x3000, "Chopper", SkylanderElement.Tech),
            new SkylanderGenericData(0x1d9, 0x3000, "Tread Head", SkylanderElement.Tech),
            new SkylanderGenericData(0x1da, 0x3000, "Bushwack", SkylanderElement.Life),
            new SkylanderGenericData(0x1da, 0x3403, "Legendary Bushwack", SkylanderElement.Life),
            new SkylanderGenericData(0x1db, 0x3000, "Tuff Luck", SkylanderElement.Life),
            new SkylanderGenericData(0x1db, 0x301D, "Tuff Luck (Clear)", SkylanderElement.Life),
            new SkylanderGenericData(0x1dc, 0x3000, "Food Fight", SkylanderElement.Life),
            new SkylanderGenericData(0x1dc, 0x3402, "Dark Food Fight", SkylanderElement.Life),
            new SkylanderGenericData(0x1dc, 0x340F, "Instant Food Fight", SkylanderElement.Life),
            new SkylanderGenericData(0x1dd, 0x3000, "High Five", SkylanderElement.Life),
            new SkylanderGenericData(0x1de, 0x3000, "Krypt King", SkylanderElement.Undead),
            new SkylanderGenericData(0x1de, 0x3402, "Nitro Krypt King", SkylanderElement.Undead),
            new SkylanderGenericData(0x1df, 0x3000, "Short Cut", SkylanderElement.Undead),
            new SkylanderGenericData(0x1df, 0x301D, "Short Cut (Clear)", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e0, 0x3000, "Bat Spin", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e1, 0x3000, "Funny Bone", SkylanderElement.Undead),
            new SkylanderGenericData(0x1e2, 0x3000, "Knight Light", SkylanderElement.Light),
            new SkylanderGenericData(0x1e3, 0x3000, "Spotlight", SkylanderElement.Light),
            new SkylanderGenericData(0x1e4, 0x3000, "Knight Mare", SkylanderElement.Dark),
            new SkylanderGenericData(0x1e5, 0x3000, "Blackout", SkylanderElement.Dark),
            new SkylanderGenericData(0x1f6, 0x3000, "Bop", SkylanderElement.Earth),
            new SkylanderGenericData(0x1f9, 0x0000, "Terrabite (Sidekick)", SkylanderElement.Earth),
            new SkylanderGenericData(0x1f9, 0x3000, "Terrabite", SkylanderElement.Earth),
            new SkylanderGenericData(0x1fa, 0x3000, "Breeze", SkylanderElement.Air),
            new SkylanderGenericData(0x1fc, 0x3000, "Pet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0x1fc, 0x3402, "Power Punch Pet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0x1fb, 0x3000, "Weeruptor", SkylanderElement.Fire),
            new SkylanderGenericData(0x1fb, 0x3402, "Eggcellent Weeruptor", SkylanderElement.Fire),
            new SkylanderGenericData(0x1fd, 0x3000, "Small Fry", SkylanderElement.Fire),
            new SkylanderGenericData(0x1fe, 0x3000, "Drobit", SkylanderElement.Tech),
            new SkylanderGenericData(0x207, 0x1000, "Trigger Snappy (Sidekick)", SkylanderElement.Tech),
            new SkylanderGenericData(0x207, 0x3000, "Trigger Snappy", SkylanderElement.Tech),
            new SkylanderGenericData(0x20e, 0x1000, "Whisper Elf (Sidekick)", SkylanderElement.Life),
            new SkylanderGenericData(0x20e, 0x3000, "Whisper Elf", SkylanderElement.Life),
            new SkylanderGenericData(0x21c, 0x1000, "Barkley (Sidekick)", SkylanderElement.Life),
            new SkylanderGenericData(0x21c, 0x3000, "Barkley", SkylanderElement.Life),
            new SkylanderGenericData(0x21c, 0x3402, "Gnarly Barkley", SkylanderElement.Life),
            new SkylanderGenericData(0x21d, 0x1000, "Thumpling (Sidekick)", SkylanderElement.Water),
            new SkylanderGenericData(0x21d, 0x3000, "Thumpling", SkylanderElement.Water),
            new SkylanderGenericData(0x202, 0x0000, "Gill Runt (Sidekick)", SkylanderElement.Water),
            new SkylanderGenericData(0x202, 0x3000, "Gill Runt", SkylanderElement.Water),
            new SkylanderGenericData(0x21e, 0x1000, "Mini-Jini (Sidekick)", SkylanderElement.Magic),
            new SkylanderGenericData(0x21e, 0x3000, "Mini-Jini", SkylanderElement.Magic),
            new SkylanderGenericData(0x1f7, 0x3000, "Spry", SkylanderElement.Magic),
            new SkylanderGenericData(0x1f8, 0x3000, "Hijinx", SkylanderElement.Undead),
            new SkylanderGenericData(0x21f, 0x1000, "Eye Small (Sidekick)", SkylanderElement.Undead),
            new SkylanderGenericData(0x21f, 0x3000, "Eye Small", SkylanderElement.Undead),
            new SkylanderGenericData(0x259, 0x5000, "King Pen", SkylanderElement.Water), 
            new SkylanderGenericData(0x259, 0x5402, "Dark King Pen", SkylanderElement.Water), 
            new SkylanderGenericData(0x25a, 0x5000, "Tri-Tip", SkylanderElement.Earth),
            new SkylanderGenericData(0x25a, 0x5403, "Lengendary Tri-Tip", SkylanderElement.Earth),
            new SkylanderGenericData(0x25b, 0x5000, "Chopscotch", SkylanderElement.Undead),
            new SkylanderGenericData(0x25b, 0x5415, "Candy-Coated Chopscotch", SkylanderElement.Undead),
            new SkylanderGenericData(0x25c, 0x5000, "Boom Bloom", SkylanderElement.Life),
            new SkylanderGenericData(0x25d, 0x5000, "Pit Boss", SkylanderElement.Undead),
            new SkylanderGenericData(0x25d, 0x5403, "Legendary Pit Boss", SkylanderElement.Undead),
            new SkylanderGenericData(0x25e, 0x5000, "Barbella", SkylanderElement.Earth),
            new SkylanderGenericData(0x25e, 0x5021, "Barbella (Pink)", SkylanderElement.Earth),
            new SkylanderGenericData(0x25f, 0x5000, "Air Strike", SkylanderElement.Air),
            new SkylanderGenericData(0x25f, 0x540D, "Egg Bomber Air Strike", SkylanderElement.Air),
            new SkylanderGenericData(0x260, 0x5000, "Ember", SkylanderElement.Fire),
            new SkylanderGenericData(0x260, 0x5004, "Dec-Ember", SkylanderElement.Fire),
            new SkylanderGenericData(0x261, 0x5000, "Ambush", SkylanderElement.Life),
            new SkylanderGenericData(0x262, 0x5000, "Dr. Krankcase", SkylanderElement.Tech),
            new SkylanderGenericData(0x263, 0x5000, "Hood Sickle", SkylanderElement.Dark),
            new SkylanderGenericData(0x263, 0x5402, "Steel Plated Hood Sickle", SkylanderElement.Dark),
            new SkylanderGenericData(0x264, 0x5000, "Tae Kwon Crow", SkylanderElement.Fire),
            new SkylanderGenericData(0x264, 0x5402, "Mystical Tae Kwon Crow", SkylanderElement.Fire),
            new SkylanderGenericData(0x265, 0x5000, "Golden Queen", SkylanderElement.Earth),
            new SkylanderGenericData(0x265, 0x5402, "Dark Golden Queen", SkylanderElement.Earth),
            new SkylanderGenericData(0x266, 0x5000, "Wolfgang", SkylanderElement.Undead),
            new SkylanderGenericData(0x266, 0x5402, "Dark Wolfgang", SkylanderElement.Undead),
            new SkylanderGenericData(0x267, 0x5000, "Pain-Yatta", SkylanderElement.Magic),
            new SkylanderGenericData(0x267, 0x5021, "Pain-Yatta (Rock Candy)", SkylanderElement.Magic),
            new SkylanderGenericData(0x268, 0x5000, "Mysticat", SkylanderElement.Magic),
            new SkylanderGenericData(0x269, 0x5000, "Starcast", SkylanderElement.Magic),
            new SkylanderGenericData(0x269, 0x5021, "Starcast (Clear)", SkylanderElement.Magic),
            new SkylanderGenericData(0x26a, 0x5000, "Buckshot", SkylanderElement.Magic),
            new SkylanderGenericData(0x26b, 0x5000, "Aurora", SkylanderElement.Light),
            new SkylanderGenericData(0x26b, 0x5402, "Solar Flare Aurora", SkylanderElement.Light),
            new SkylanderGenericData(0x26c, 0x5000, "Flare Wolf", SkylanderElement.Fire),
            new SkylanderGenericData(0x26c, 0x540D, "Hard-Boiled Flare Wolf", SkylanderElement.Fire),
            new SkylanderGenericData(0x26d, 0x5000, "Chompy Mage", SkylanderElement.Life),
            new SkylanderGenericData(0x26d, 0x540E, "Jingle Bell Chompy Mage", SkylanderElement.Life),
            new SkylanderGenericData(0x26e, 0x5000, "Bad Juju", SkylanderElement.Air),
            new SkylanderGenericData(0x26e, 0x5402, "Mystical Bad Juju", SkylanderElement.Air),
            new SkylanderGenericData(0x26f, 0x5000, "Grave Clobber", SkylanderElement.Undead),
            new SkylanderGenericData(0x270, 0x5000, "Blaster-Tron", SkylanderElement.Light),
            new SkylanderGenericData(0x271, 0x5000, "Ro-Bow", SkylanderElement.Tech),
            new SkylanderGenericData(0x272, 0x5000, "Chain Reaction", SkylanderElement.Tech),
            new SkylanderGenericData(0x272, 0x5021, "Chain Reaction (Orange)", SkylanderElement.Tech),
            new SkylanderGenericData(0x273, 0x5000, "Kaos", SkylanderElement.Kaos),
            new SkylanderGenericData(0x274, 0x5000, "Wild Storm", SkylanderElement.Air),
            new SkylanderGenericData(0x275, 0x5000, "Tidepool", SkylanderElement.Water),
            new SkylanderGenericData(0x276, 0x5000, "Crash Bandicoot", SkylanderElement.Life),
            new SkylanderGenericData(0x277, 0x5000, "Dr. Neo Cortex", SkylanderElement.Tech), 
            new SkylanderGenericData(0x2A8, 0x5204,  "Magic Creation Crystal (Pyramid)", SkylanderElement.Magic, SkylanderType.Crystal),
            new SkylanderGenericData(0x2A8, 0x5208,  "Magic Creation Crystal (Lantern)", SkylanderElement.Magic, SkylanderType.Crystal),
            new SkylanderGenericData(0x2A8, 0x5608,  "Magic Creation Crystal (Lantern)", SkylanderElement.Magic, SkylanderType.Crystal),
            new SkylanderGenericData(0x2A8, 0x521B,  "Magic Creation Crystal (Claw)", SkylanderElement.Magic, SkylanderType.Crystal),
            new SkylanderGenericData(0x2A9, 0x5214,  "Water Creation Crystal (Armor)", SkylanderElement.Water, SkylanderType.Crystal),
            new SkylanderGenericData(0x2A9, 0x5218,  "Water Creation Crystal (Fanged)", SkylanderElement.Water, SkylanderType.Crystal),
            new SkylanderGenericData(0x2A9, 0x521C,  "Water Creation Crystal (Rocket)", SkylanderElement.Water, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AA, 0x5202,  "Air Creation Crystal (Angel)", SkylanderElement.Air, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AA, 0x5207,  "Air Creation Crystal (Lantern)", SkylanderElement.Air, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AA, 0x5212,  "Air Creation Crystal (Acorn)", SkylanderElement.Air, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AB, 0x5209,  "Undead Creation Crystal (Lantern)", SkylanderElement.Undead, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AB, 0x5217,  "Undead Creation Crystal (Fanged)", SkylanderElement.Undead, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AB, 0x5219,  "Undead Creation Crystal (Claw)", SkylanderElement.Undead, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AC, 0x5205,  "Tech Creation Crystal (Pyramid)", SkylanderElement.Tech, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AC, 0x520D,  "Tech Creation Crystal (Reactor)", SkylanderElement.Tech, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AC, 0x5215,  "Tech Creation Crystal (Armor)", SkylanderElement.Tech, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AD, 0x5201,  "Fire Creation Crystal (Angel)", SkylanderElement.Fire, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AD, 0x520F,  "Fire Creation Crystal (Reactor)", SkylanderElement.Fire, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AD, 0x5211,  "Fire Creation Crystal (Acorn)", SkylanderElement.Fire, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AE, 0x520C,  "Earth Creation Crystal (Rune)", SkylanderElement.Earth, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AE, 0x5213,  "Earth Creation Crystal (Armor)", SkylanderElement.Earth, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AE, 0x521D,  "Earth Creation Crystal (Rocket)", SkylanderElement.Earth, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AF, 0x5210,  "Life Creation Crystal (Acorn)", SkylanderElement.Life, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AF, 0x5610,  "Life Creation Crystal (Acorn)", SkylanderElement.Life, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AF, 0x521A,  "Life Creation Crystal (Claw)", SkylanderElement.Life, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AF, 0x521E,  "Life Creation Crystal (Rocket)", SkylanderElement.Life, SkylanderType.Crystal),
            new SkylanderGenericData(0x2AF, 0x521F,  "Life Creation Crystal (Rune)", SkylanderElement.Life, SkylanderType.Crystal),
            new SkylanderGenericData(0x2B0, 0x5206,  "Dark Creation Crystal (Pyramid)", SkylanderElement.Dark, SkylanderType.Crystal),
            new SkylanderGenericData(0x2B0, 0x520A,  "Dark Creation Crystal (Rune)", SkylanderElement.Dark, SkylanderType.Crystal),
            new SkylanderGenericData(0x2B0, 0x520E,  "Dark Creation Crystal (Reactor)", SkylanderElement.Dark, SkylanderType.Crystal),
            new SkylanderGenericData(0x2B1, 0x5203,  "Light Creation Crystal (UNRELEASED Angel)", SkylanderElement.Light, SkylanderType.Crystal),
            new SkylanderGenericData(0x2B1, 0x520B,  "Light Creation Crystal (Rune)", SkylanderElement.Light, SkylanderType.Crystal),
            new SkylanderGenericData(0x2B1, 0x5216,  "Light Creation Crystal (Fanged)", SkylanderElement.Light, SkylanderType.Crystal),
            new SkylanderGenericData(0x2B1, 0x5616,  "Light Creation Crystal (Legendary Fanged)", SkylanderElement.Light, SkylanderType.Crystal),
            new SkylanderGenericData(0x3e8, 0x2000, "Boom Jet (Bottom)", SkylanderElement.Air),
            new SkylanderGenericData(0x3e9, 0x2000, "Free Ranger (Bottom)", SkylanderElement.Air),
            new SkylanderGenericData(0x3e9, 0x2403, "Legendary Free Ranger (Bottom)", SkylanderElement.Air),
            new SkylanderGenericData(0x3ea, 0x2000, "Rubble Rouser (Bottom)", SkylanderElement.Earth),
            new SkylanderGenericData(0x3eb, 0x2000, "Doom Stone (Bottom)", SkylanderElement.Earth),
            new SkylanderGenericData(0x3eb, 0x2016, "Doom Stone (Bottom Bronze)", SkylanderElement.Earth),
            new SkylanderGenericData(0x3ec, 0x2000, "Blast Zone (Bottom)", SkylanderElement.Fire),
            new SkylanderGenericData(0x3ec, 0x2402, "Dark Blast Zone (Bottom)", SkylanderElement.Fire),
            new SkylanderGenericData(0x3ed, 0x2000, "Fire Kraken (Bottom)", SkylanderElement.Fire),
            new SkylanderGenericData(0x3ed, 0x2016, "Fire Kraken (Bottom Gold)", SkylanderElement.Fire),
            new SkylanderGenericData(0x3ed, 0x2402, "Jade Fire Kraken (Bottom)", SkylanderElement.Fire),
            new SkylanderGenericData(0x3ee, 0x2000, "Stink Bomb (Bottom)", SkylanderElement.Life),
            new SkylanderGenericData(0x3ee, 0x2016, "Stink Bomb (Bottom Gold)", SkylanderElement.Life),
            new SkylanderGenericData(0x3ef, 0x2000, "Grilla Drilla (Bottom)", SkylanderElement.Life),
            new SkylanderGenericData(0x3f0, 0x2000, "Hoot Loop (Bottom)", SkylanderElement.Magic),
            new SkylanderGenericData(0x3f0, 0x2402, "Enchanted Hoot Loop (Bottom)", SkylanderElement.Magic),
            new SkylanderGenericData(0x3f1, 0x2000, "Trap Shadow (Bottom)", SkylanderElement.Magic),
            new SkylanderGenericData(0x3f1, 0x2016, "Trap Shadow (Bottom Silver)", SkylanderElement.Magic),
            new SkylanderGenericData(0x3f2, 0x2000, "Magna Charge (Bottom)", SkylanderElement.Magic),
            new SkylanderGenericData(0x3f2, 0x2402, "Nitro Magna Charge (Bottom)", SkylanderElement.Tech),
            new SkylanderGenericData(0x3f3, 0x2000, "Spy Rise (Bottom)", SkylanderElement.Tech),
            new SkylanderGenericData(0x3f4, 0x2000, "Night Shift (Bottom)", SkylanderElement.Undead),
            new SkylanderGenericData(0x3f4, 0x2403, "Legendary Night Shift (Bottom)", SkylanderElement.Undead),
            new SkylanderGenericData(0x3f5, 0x2000, "Rattle Shake (Bottom)", SkylanderElement.Undead),
            new SkylanderGenericData(0x3f5, 0x2402, "Quick Draw Rattle Shake (Bottom)", SkylanderElement.Undead),
            new SkylanderGenericData(0x3f6, 0x2000, "Freeze Blade (Bottom)", SkylanderElement.Water),
            new SkylanderGenericData(0x3f6, 0x2402, "Nitro Freeze Blade (Bottom)", SkylanderElement.Water),
            new SkylanderGenericData(0x3f7, 0x2000, "Wash Buckler (Bottom)", SkylanderElement.Water),
            new SkylanderGenericData(0x3f7, 0x2402, "Dark Wash Buckler (Bottom)", SkylanderElement.Water),
            new SkylanderGenericData(0x3f7, 0x2018, "Wash Buckler (Bottom Color Shift)", SkylanderElement.Water),
            new SkylanderGenericData(0x7cf, 0x2000, "Template Template (Bottom)"),
            new SkylanderGenericData(0x7d0, 0x2000, "Boom Jet (Top)", SkylanderElement.Air),
            new SkylanderGenericData(0x7d1, 0x2000, "Free Ranger (Top)", SkylanderElement.Air),
            new SkylanderGenericData(0x7d1, 0x2403, "Legendary Free Ranger (Top)", SkylanderElement.Air),
            new SkylanderGenericData(0x7d2, 0x2000, "Rubble Rouser (Top)", SkylanderElement.Earth),
            new SkylanderGenericData(0x7d3, 0x2000, "Doom Stone (Top)", SkylanderElement.Earth),
            new SkylanderGenericData(0x7d3, 0x2016, "Doom Stone (Top Gold)", SkylanderElement.Earth),
            new SkylanderGenericData(0x7d4, 0x2000, "Blast Zone (Top)", SkylanderElement.Fire),
            new SkylanderGenericData(0x7d4, 0x2402, "Dark Blast Zone (Top)", SkylanderElement.Fire),
            new SkylanderGenericData(0x7d5, 0x2000, "Fire Kraken (Top)", SkylanderElement.Fire),
            new SkylanderGenericData(0x7d5, 0x2402, "Jade Fire Kraken (Top)", SkylanderElement.Fire),
            new SkylanderGenericData(0x7d6, 0x2000, "Stink Bomb (Top)", SkylanderElement.Life),
            new SkylanderGenericData(0x7d6, 0x2016, "Stink Bomb (Top Silver)", SkylanderElement.Life),
            new SkylanderGenericData(0x7d7, 0x2000, "Grilla Drilla (Top)", SkylanderElement.Life),
            new SkylanderGenericData(0x7d8, 0x2000, "Hoot Loop (Top)", SkylanderElement.Magic),
            new SkylanderGenericData(0x7d8, 0x2402, "Enchanted Hoot Loop (Top)", SkylanderElement.Magic),
            new SkylanderGenericData(0x7d9, 0x2000, "Trap Shadow (Top)", SkylanderElement.Magic),
            new SkylanderGenericData(0x7d9, 0x2016, "Trap Shadow (Top Bronze)", SkylanderElement.Magic),
            new SkylanderGenericData(0x7da, 0x2000, "Magna Charge (Top)", SkylanderElement.Tech),
            new SkylanderGenericData(0x7da, 0x2402, "Nitro Magna Charge (Top)", SkylanderElement.Tech),
            new SkylanderGenericData(0x7db, 0x2000, "Spy Rise (Top)", SkylanderElement.Tech),
            new SkylanderGenericData(0x7dc, 0x2000, "Night Shift (Top)", SkylanderElement.Undead),
            new SkylanderGenericData(0x7dc, 0x2403, "Legendary Night Shift (Top)", SkylanderElement.Undead),
            new SkylanderGenericData(0x7dd, 0x2000, "Rattle Shake (Top)", SkylanderElement.Undead),
            new SkylanderGenericData(0x7dd, 0x2402, "Quick Draw Rattle Shake (Top)", SkylanderElement.Undead),
            new SkylanderGenericData(0x7de, 0x2000, "Freeze Blade (Top)", SkylanderElement.Water),
            new SkylanderGenericData(0x7de, 0x2402, "Nitro Freeze Blade (Top)", SkylanderElement.Water),
            new SkylanderGenericData(0x7df, 0x2000, "Wash Buckler (Top)", SkylanderElement.Water),
            new SkylanderGenericData(0x7df, 0x2018, "Wash Buckler (Top Color Shift)", SkylanderElement.Water),
            new SkylanderGenericData(0x7df, 0x2402, "Dark Wash Buckler (Top)", SkylanderElement.Water),
            new SkylanderGenericData(0xbb7, 0x2000, "Template Template (Top)"),
            new SkylanderGenericData(0xbb8, 0x2000, "Scratch", SkylanderElement.Air),
            new SkylanderGenericData(0xbb9, 0x2000, "Pop Thorn", SkylanderElement.Air),
            new SkylanderGenericData(0xbba, 0x2000, "Slobber Tooth", SkylanderElement.Earth),
            new SkylanderGenericData(0xbba, 0x2402, "Dark Slobber Tooth", SkylanderElement.Earth),
            new SkylanderGenericData(0xbbb, 0x2000, "Scorp", SkylanderElement.Earth),
            new SkylanderGenericData(0xbbc, 0x2000, "Fryno", SkylanderElement.Fire),
            new SkylanderGenericData(0xbbc, 0x3805, "Hog Wild Fryno", SkylanderElement.Fire),
            new SkylanderGenericData(0xbbd, 0x2000, "Smolderdash", SkylanderElement.Fire),
            new SkylanderGenericData(0xbbd, 0x2206, "Smolderdash (LightCore)", SkylanderElement.Fire),
            new SkylanderGenericData(0xbbe, 0x2000, "Bumble Blast", SkylanderElement.Life),
            new SkylanderGenericData(0xbbe, 0x2402, "Jolly Bumble Blast", SkylanderElement.Life),
            new SkylanderGenericData(0xbbe, 0x2206, "Bumble Blast (LightCore)", SkylanderElement.Life),
            new SkylanderGenericData(0xbbf, 0x2000, "Zoo Lou", SkylanderElement.Life),
            new SkylanderGenericData(0xbbf, 0x2403, "Legendary Zoo Lou", SkylanderElement.Life),
            new SkylanderGenericData(0xbc0, 0x2000, "Dune Bug", SkylanderElement.Magic),
            new SkylanderGenericData(0xbc0, 0x2004, "Dune Bug (Red)", SkylanderElement.Magic),
            new SkylanderGenericData(0xbc1, 0x2000, "Star Strike", SkylanderElement.Magic),
            new SkylanderGenericData(0xbc1, 0x2602, "Enchanted Star Strike", SkylanderElement.Magic),
            new SkylanderGenericData(0xbc1, 0x2206, "Star Strike (LightCore)", SkylanderElement.Magic),
            new SkylanderGenericData(0xbc2, 0x2000, "Countdown", SkylanderElement.Tech),
            new SkylanderGenericData(0xbc2, 0x2402, "Kickoff Countdown", SkylanderElement.Tech),
            new SkylanderGenericData(0xbc2, 0x2206, "Countdown (LightCore)", SkylanderElement.Tech),
            new SkylanderGenericData(0xbc3, 0x2000, "Wind Up", SkylanderElement.Tech),
            new SkylanderGenericData(0xbc4, 0x2000, "Roller Brawl", SkylanderElement.Undead),
            new SkylanderGenericData(0xbc5, 0x2000, "Grim Creeper", SkylanderElement.Undead),
            new SkylanderGenericData(0xbc5, 0x2603, "Legendary Grim Creeper", SkylanderElement.Undead),
            new SkylanderGenericData(0xbc5, 0x2206, "Grim Creeper (LightCore)", SkylanderElement.Undead),
            new SkylanderGenericData(0xbc6, 0x2000, "Rip Tide", SkylanderElement.Water),
            new SkylanderGenericData(0xbc6, 0x2016, "Rip Tide (Green)", SkylanderElement.Water),
            new SkylanderGenericData(0xbc7, 0x2000, "Punk Shock", SkylanderElement.Water),
            new SkylanderGenericData(0xc80, 0x2000, "Battle Hammer", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xc81, 0x2000, "Sky Diamond", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xc82, 0x2000, "Platinum Sheep", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xc83, 0x2000, "Groove Machine", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xc84, 0x2000, "UFO Hat", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xce4, 0x2000, "Sheep Wreck Island", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0xce5, 0x2000, "Tower of Time", type: SkylanderType.AdventurePack),
            new SkylanderGenericData(0xce6, 0x2206, "Fiery Forge", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xce7, 0x2206, "Arkeyan Crossbow", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xc94, 0x4000, "Jet Stream", SkylanderElement.Air, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc95, 0x4000, "Tomb Buggy", SkylanderElement.Undead, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc95, 0x401E, "Tomb Buggy (Dark Bronze)", SkylanderElement.Undead, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc96, 0x4000, "Reef Ripper", SkylanderElement.Water, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc97, 0x4000, "Burn Cycle", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc97, 0x401E, "Burn Cycle (Patina)", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc98, 0x4000, "Hot Streak", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc98, 0x4402, "Dark Hot Streak", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc98, 0x4004, "E3 Hot Streak", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc98, 0x401F, "Hot Streak (Mobile Starter)", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc98, 0x441E, "Golden Hot Streak", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc98, 0x440F, "Instant Hot Streak", SkylanderElement.Fire, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc99, 0x4000, "Shark Tank", SkylanderElement.Earth, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc9a, 0x4000, "Thump Truck", SkylanderElement.Earth, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc9b, 0x4000, "Crypt Crusher", SkylanderElement.Undead, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc9c, 0x4000, "Stealth Stinger", SkylanderElement.Life, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc9c, 0x4402, "Nitro Stealth Stinger", SkylanderElement.Life, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc9f, 0x4000, "Dive Bomber", SkylanderElement.Water, SkylanderType.Vehicle),
            new SkylanderGenericData(0xc9f, 0x4402, "Spring Ahead Dive Bomber", SkylanderElement.Water, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca0, 0x4000, "Sky Slicer", SkylanderElement.Air, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca0, 0x440F, "Instant Sky Slicer", SkylanderElement.Air, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca1, 0x4000, "Clown Cruiser", SkylanderElement.Air, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca1, 0x4402, "Dark Clown Cruiser", SkylanderElement.Air, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca2, 0x4000, "Gold Rusher", SkylanderElement.Tech, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca2, 0x4402, "Power Blue Gold Rusher", SkylanderElement.Tech, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca3, 0x4000, "Shield Striker", SkylanderElement.Tech, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca3, 0x401E, "Shield Striker (Patina)", SkylanderElement.Tech, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca4, 0x4000, "Sun Runner", SkylanderElement.Light, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca4, 0x439F, "Legendary Sun Runner", SkylanderElement.Light, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca5, 0x4000, "Sea Shadow", SkylanderElement.Dark, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca5, 0x4402, "Dark Sea Shadow", SkylanderElement.Dark, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca5, 0x440F, "Instant Sea Shadow", SkylanderElement.Dark, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca6, 0x4000, "Splatter Splasher", SkylanderElement.Magic, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca6, 0x4402, "Power Blue Splatter Splasher", SkylanderElement.Magic, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca7, 0x4000, "Soda Skimmer", SkylanderElement.Magic, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca7, 0x4402, "Nitro Soda Skimmer", SkylanderElement.Magic, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca8, 0x4000, "Barrel Blaster", SkylanderElement.Tech, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca8, 0x4402, "Dark Barrel Blaster", SkylanderElement.Tech, SkylanderType.Vehicle),
            new SkylanderGenericData(0xca9, 0x4000, "Buzz Wing", SkylanderElement.Life, SkylanderType.Vehicle),
            new SkylanderGenericData(0xd48, 0x4100, "Fiesta", SkylanderElement.Undead),
            new SkylanderGenericData(0xd48, 0x4515, "Frightful Fiesta", SkylanderElement.Undead),
            new SkylanderGenericData(0xd49, 0x4100, "High Volt", SkylanderElement.Tech),
            new SkylanderGenericData(0xd49, 0x411E, "High Volt (Patina)", SkylanderElement.Tech),
            new SkylanderGenericData(0xd4a, 0x4100, "Splat", SkylanderElement.Magic),
            new SkylanderGenericData(0xd4a, 0x4502, "Power Blue Splat", SkylanderElement.Magic),
            new SkylanderGenericData(0xd4e, 0x4100, "Stormblade", SkylanderElement.Air),
            new SkylanderGenericData(0xd4e, 0x410E, "Snow-Brite Stormblade", SkylanderElement.Air),
            new SkylanderGenericData(0xd53, 0x4000, "Smash Hit", SkylanderElement.Earth),
            new SkylanderGenericData(0xd53, 0x4502, "Steel Plated Smash Hit", SkylanderElement.Earth),
            new SkylanderGenericData(0xd54, 0x4100, "Spitfire", SkylanderElement.Fire),
            new SkylanderGenericData(0xd54, 0x4502, "Dark Spitfire", SkylanderElement.Fire),
            new SkylanderGenericData(0xd55, 0x4100, "Hurricane Jet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0xd55, 0x4503, "Legendary Hurricane Jet Vac", SkylanderElement.Air),
            new SkylanderGenericData(0xd56, 0x4100, "Double Dare Trigger Happy", SkylanderElement.Tech),
            new SkylanderGenericData(0xd56, 0x4502, "Power Blue Double Dare Trigger Happy", SkylanderElement.Tech),
            new SkylanderGenericData(0xd57, 0x4100, "Super Shot Stealth Elf", SkylanderElement.Life),
            new SkylanderGenericData(0xd57, 0x4502, "Dark Super Shot Stealth Elf", SkylanderElement.Life),
            new SkylanderGenericData(0xd57, 0x450F, "Instant Super Shot Stealth Elf", SkylanderElement.Life),
            new SkylanderGenericData(0xd58, 0x4100, "Shark Shooter Terrafin", SkylanderElement.Earth),
            new SkylanderGenericData(0xd59, 0x4100, "Bone Bash Roller Brawl", SkylanderElement.Undead),
            new SkylanderGenericData(0xd59, 0x411E, "Bone Bash Roller Brawl (Bronze)", SkylanderElement.Undead),
            new SkylanderGenericData(0xd59, 0x4503, "Legendary Bone Bash Roller Brawl", SkylanderElement.Undead),
            new SkylanderGenericData(0xd5c, 0x4100, "Big Bubble Pop Fizz", SkylanderElement.Magic),
            new SkylanderGenericData(0xd5c, 0x450E, "Birthday Bash Big Bubble Pop Fizz", SkylanderElement.Magic),
            new SkylanderGenericData(0xd5d, 0x4100, "Lava Lance Eruptor", SkylanderElement.Fire),
            new SkylanderGenericData(0xd5d, 0x411E, "Lava Lance Eruptor (Patina)", SkylanderElement.Fire),
            new SkylanderGenericData(0xd5e, 0x4100, "Deep Dive Gill Grunt", SkylanderElement.Water),
            new SkylanderGenericData(0xd5f, 0x4100, "Turbo Charge Donkey Kong", SkylanderElement.Life),
            new SkylanderGenericData(0xd5f, 0x4502, "Dark Turbo Charge Donkey Kong", SkylanderElement.Life),
            new SkylanderGenericData(0xd60, 0x4100, "Hammer Slam Bowser", SkylanderElement.Fire),
            new SkylanderGenericData(0xd60, 0x4502, "Dark Hammer Slam Bowser", SkylanderElement.Fire),
            new SkylanderGenericData(0xd61, 0x4100, "Dive-Clops", SkylanderElement.Water),
            new SkylanderGenericData(0xd61, 0x450E, "Missile-Tow Dive-Clops", SkylanderElement.Water),
            new SkylanderGenericData(0xd61, 0x450F, "Instant Dive-Clops", SkylanderElement.Water),
            new SkylanderGenericData(0xd62, 0x4100, "Astroblast", SkylanderElement.Light),
            new SkylanderGenericData(0xd62, 0x4503, "Legendary Astroblast", SkylanderElement.Light),
            new SkylanderGenericData(0xd63, 0x4100, "Nightfall", SkylanderElement.Dark),
            new SkylanderGenericData(0xd64, 0x4100, "Thrillipede", SkylanderElement.Life),
            new SkylanderGenericData(0xd64, 0x450D, "Eggcited Thrillipede", SkylanderElement.Life),
            new SkylanderGenericData(0xdac, 0x4000, "Sky Trophy", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xdad, 0x4000, "Land Trophy", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xdae, 0x4000, "Sea Trophy", type: SkylanderType.MagicItem),
            new SkylanderGenericData(0xdaf, 0x4000, "Kaos Trophy", type: SkylanderType.MagicItem),
        };
    }
}